HRPortal.UI/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.Models;
using HRPortal.UI.Models;

namespace HRPortal.UI.Controllers
{
    public class ApplicantController : Controller
    {
        private RepoOperations _rops = new RepoOperations();

        // GET: Applicant
        public ActionResult Index()
        {
            return View();
        }

        // GET
        public ActionResult CreateApp()
        {
            var newApplication = new CreateAppVM();
            newApplication.ApplicationInfo = new Resume();
            newApplication.CreatePositionsList(_rops.ReturnListOfPositions());
            newApplication.CreateStateList(_rops.ReturnListOfStates());
            newApplication.CreateDegreesList();

            Experience newExp = new Experience();
            newApplication.ApplicationInfo.Experiences.Add(newExp);
            EducationInfo newEdu = new EducationInfo();
            newApplication.ApplicationInfo.Education.Add(newEdu);

            newApplication.ApplicationInfo.AppId = _rops.HighestAppIDNum() + 1;

            return View(newApplication);
        }

        [HttpPost]
        public ActionResult CreateApp(CreateAppVM newAppInfo)
        {
            newAppInfo.CreateStateList(_rops.ReturnListOfStates());
            newAppInfo.CreatePositionsList(_rops.ReturnListOfPositions());
            newAppInfo.CreateDegreesList();
            
            if (ModelState.IsValid)
            {
                _rops.AddAppToRepo(newAppInfo.ApplicationInfo);

                return View("Confirmation", newAppInfo.ApplicationInfo);
            }

            return View(newAppInfo);
        }
    }
}

HRPortal.UI/Views/Applicant/Confirmation.cshtml
@model HRPortal.Models.Resume

@{
    ViewBag.Title = "Confirmation of Your New Application";
}

<h2>Confirmation Page</h2>

<table class="table-striped">
    <tbody>
        <tr>
            <td>Prefix</td>
            <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Prefix)</td>
        </tr>
        <tr>
            <td>First Name</td>
            <td>@Html.DisplayFor(m => m.ApplicantContactInfo.FirstName)</td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td>@Html.DisplayFor(m => m.ApplicantContactInfo.LastName)</td>
        </tr>
        <tr>
            <td>Suffix</td>
            <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Suffix)</td>
        </tr>
    <tr>
        <td>Email</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Email)</td>
    </tr>
    <tr>
        <td>Phone Number</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.PhoneNumber)</td>
    </tr>
    <tr>
        <td>Address Line 1</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Address.AddressLine1)</td>
    </tr>
    <tr>
        <td>Address Line 2</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Address.AddressLine2)</td>
    </tr>
    <tr>
        <td>City</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Address.City)</td>
    </tr>
    <tr>
        <td>State</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Address.State)</td>
    </tr>
    <tr>
        <td>Zip Code</td>
        <td>@Html.DisplayFor(m => m.ApplicantContactInfo.Address.Zipcode)</td>
    </tr>
    <tr>
        <td>Desired Position</td>
        <td>@Html.DisplayFor(m => m.Position.PositionName)</td>
    </tr>
        <tr>
            <td>Desired Salary</td>
            <td>@Html.DisplayFor(m => m.DesiredSalary)</td>
        </tr>

        @*<li>Prefix: @Html.DisplayFor(m => m.ApplicantContactInfo.Prefix)</li>
            <li>First Name: @Html.DisplayFor(m => m.ApplicantContactInfo.FirstName)</li>
            <li>Last Name: @Html.DisplayFor(m => m.ApplicantContactInfo.LastName)</li>
            <li>Suffix: @Html.DisplayFor(m => m.ApplicantContactInfo.Suffix)</li>
            <li>Email: @Html.DisplayFor(m => m.ApplicantContactInfo.Email)</li>
            <li>Phone Number: @Html.DisplayFor(m => m.ApplicantContactInfo.PhoneNumber)</li>
            <li>Address Line 1: @Html.DisplayFor(m => m.ApplicantContactInfo.Address.AddressLine1)</li>
            <li>Address Line 2: @Html.DisplayFor(m => m.ApplicantContactInfo.Address.AddressLine2)</li>
            <li>City: @Html.DisplayFor(m => m.ApplicantContactInfo.Address.City)</li>
            <li>State: @Html.DisplayFor(m => m.ApplicantContactInfo.Address.State)</li>
            <li>Zipcode*: @Html.DisplayFor(m => m.ApplicantContactInfo.Address.Zipcode)</li>
            <li>Desired Position: @Html.DisplayFor(m => m.Position.PositionId)</li>
            <li>Education Degree: @Html.DisplayFor(m => m.Education[0].Degree.DegreeAbbr)</li>
            <li>Desired Salary: @Html.DisplayFor(m => m.DesiredSalary)</li>
            <li>Date of Application: @Html.DisplayFor(m => m.AppDate)</li>*@

        @foreach (var edu in Model.Education)
        {
            <tr>
                <td>Degree</td>
                <td>@Html.DisplayFor(m => edu.Degree.DegreeAbbr)</td>
            </tr>
            <tr>
                <td>Institution</td>
                <td>@Html.DisplayFor(m => edu.Institution)</td>
            </tr>
            <tr>
                <td>City</td>
                <td>@Html.DisplayFor(m => edu.Location.City)</td>
            </tr>
            <tr>
                <td>State</td>
                <td>@Html.DisplayFor(m => edu.Location.State)</td>
            </tr>
            <tr>
                <td>Concentration</td>
                <td>@Html.DisplayFor(m => edu.Concentration)</td>
            </tr>
            <tr>
                <td>GPA</td>
                <td>@Html.DisplayFor(m => edu.GPA)</td>
            </tr>
            <tr>
                <td>Graduation Date</td>
                <td>@Html.DisplayFor(m => edu.GraduationDate)</td>
            </tr>
            <tr>
                <td>Enrollment Date</td>
                <td>@Html.DisplayFor(m => edu.StartDate)</td>
            </tr>
        }
        @foreach (var exp in Model.Experiences)
        {
            <tr>
                <td>Title</td>
                <td>@Html.DisplayFor(m => exp.Title)</td>
            </tr>
            <tr>
                <td>Company</td>
                <td>@Html.DisplayFor(m => exp.Company)</td>
            </tr>
            <tr>
                <td>City</td>
                <td>@Html.DisplayFor(m => exp.Location.City)</td>
            </tr>
            <tr>
                <td>State</td>
                <td>@Html.DisplayFor(m => exp.Location.State)</td>
            </tr>
            <tr>
                <td>Start Date</td>
                <td>@Html.DisplayFor(m => exp.StartDate)</td>
            </tr>
            <tr>
                <td>End Date</td>
                <td>@Html.DisplayFor(m => exp.EndDate)</td>
            </tr>
            <tr>
                <td>Supervisor Name</td>
                <td>@Html.DisplayFor(m => exp.SupervisorName)</td>
            </tr>
            <tr>
                <td>Supervisor Email</td>
                <td>@Html.DisplayFor(m => exp.SupervisorEmail)</td>
            </tr>
            <tr>
                <td>Supervisor Phone Number</td>
                <td>@Html.DisplayFor(m => exp.SupervisorPhone)</td>
            </tr>
            <tr>
                <td>Description</td>
                <td>@Html.DisplayFor(m => exp.Description)</td>
            </tr>
        }
        <tr>
            <td>Date of Application</td>
            <td>@Html.DisplayFor(m => m.AppDate)</td>
        </tr>

    </tbody>
</table>
<br/>
@Html.ActionLink("Return to Applicant Page", "Index", "Applicant", null, new { @class = "btn btn-danger" })

HRPortal.UI/Views/Applicant/CreateApp.cshtml
@model HRPortal.UI.Models.CreateAppVM

@{
    ViewBag.Title = "Create New Application";
}

<h2>Submit a New Application</h2>

@using (Html.BeginForm("CreateApp", "Applicant", FormMethod.Post))
{
    @Html.Partial("_CreateAppView", Model)

    @*@Html.HiddenFor(m => m.ApplicationInfo.AppId)
    @Html.ValidationSummary(true)

    /*Contact Info*/
    <p>Prefix: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Prefix, new { htmlAttributes = new { placeholder = "Prefix" } })</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.FirstName)</p>
    <p>First Name*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.FirstName, new { htmlAttributes = new { placeholder = "First Name" } })</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.LastName)</p>
    <p>Last Name*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.LastName, new { htmlAttributes = new { placeholder = "Last Name" } })</p>
    <p>Suffix: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Suffix, new { htmlAttributes = new { placeholder = "Suffix" } })</p>

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Email)</p>
    <p>Email*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Email, new { htmlAttributes = new { placeholder = "Email" } })</p>

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.PhoneNumber)</p>
    <p>Phone Number*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.PhoneNumber, new { htmlAttributes = new { placeholder = "Phone Number" } })</p>

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.AddressLine1)</p>
    <p>Address Line 1*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.AddressLine1, new { htmlAttributes = new { placeholder = "Address Line 1" } })</p>
    <p>Address Line 2: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.AddressLine2, new { htmlAttributes = new { placeholder = "Address Line 2" } })</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.City)</p>
    <p>City*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.City, new { htmlAttributes = new { placeholder = "City" } })</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.State)</p>
    <p>State*: @Html.DropDownListFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.State, Model.States, new { htmlAttributes = new { placeholder = "State" } })</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.Zipcode)</p>
    <p>Zipcode*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.Zipcode, new { htmlAttributes = new { placeholder = "Zip Code" } })</p>

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.Position.PositionName)</p>
    <p>Desired Position*: @Html.DropDownListFor(m => m.ApplicationInfo.Position.PositionName, Model.Positions)</p>

    <p>@Html.LabelFor(m => m.ApplicationInfo.Experiences)</p>
    <p>
        @for (var i = 0; i < 1; i++)
        {
        <p>Company: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].Company, new { htmlAttributes = new { placeholder = "Company Name" } })</p>
        <p>Title: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].Title, new { htmlAttributes = new { placeholder = "Title" } })</p>
        <p>City: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].Location.City, new { htmlAttributes = new { placeholder = "City" } })</p>
            <p>State: @Html.DropDownListFor(m => m.ApplicationInfo.Experiences[i].Location.State, Model.States, new { htmlAttributes = new { placeholder = "State" } })</p>
            <p>Start Date: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].StartDate)</p>
            <p>End Date: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].EndDate)</p>
            <p>Supervisor Name: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].SupervisorName, new { htmlAttributes = new { placeholder = "Supervisor's Name" } })</p>
            <p>Supervisor Phone Number: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].SupervisorPhone, new { htmlAttributes = new { placeholder = "Supervisor's Phone Number" } })</p>
            <p>Supervisor Email: @Html.EditorFor(m => m.ApplicationInfo.Experiences[i].SupervisorEmail, new { htmlAttributes = new { placeholder = "Supervisor's Email" } })</p>
        }</p>

        <p>@Html.LabelFor(m => m.ApplicationInfo.Education)</p>
        <p>
            @for (var i = 0; i < 1; i++)
            {
            <p>Degree Type: @Html.DropDownListFor(m => m.ApplicationInfo.Education[i].Degree.DegreeAbbr, Model.Degrees)</p>
            <p>Institution Name: @Html.EditorFor(m => m.ApplicationInfo.Education[i].Institution, new { htmlAttributes = new { placeholder = "Institution Name" } })</p>
            <p>City: @Html.EditorFor(m => m.ApplicationInfo.Education[i].Location.City, new { htmlAttributes = new { placeholder = "City" } })</p>
            <p>State: @Html.DropDownListFor(m => m.ApplicationInfo.Education[i].Location.State, Model.States, new { htmlAttributes = new { placeholder = "State" } })</p>
            <p>Start Date: @Html.EditorFor(m => m.ApplicationInfo.Education[i].StartDate)</p>
            <p>Graduation Date: @Html.EditorFor(m => m.ApplicationInfo.Education[i].GraduationDate)</p>
            <p>GPA: @Html.EditorFor(m => m.ApplicationInfo.Education[i].GPA, new { htmlAttributes = new { placeholder = "GPA" } })</p>
            <p>Concentration: @Html.EditorFor(m => m.ApplicationInfo.Education[i].Concentration, new { htmlAttributes = new { placeholder = "Concentration" } })</p>
            }
            </p>

            <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.DesiredSalary)</p>
            <p>Desired Salary*: @Html.EditorFor(m => m.ApplicationInfo.DesiredSalary, new { htmlAttributes = new { placeholder = "Desired Salary" } })</p>

            <p>Date of Application: @Html.EditorFor(m => m.ApplicationInfo.AppDate)</p>
            <br />
            <button type="submit" class="btn btn-success">Submit</button>
            <button type="reset" class="btn btn-danger">Reset</button>*@

}

HRPortal.UI/Views/Applicant/DirectApply.cshtml
@model HRPortal.UI.Models.CreateAppVM

@{
    ViewBag.Title = "DirectApply";
    Layout = "~/Views/Shared/_LayoutDirectApply.cshtml";
}

<h2>Submit your application here!!</h2>

@using (Html.BeginForm("DirectApply", "Applicant", FormMethod.Post))
{
    @Html.HiddenFor(m => m.ApplicationInfo.AppId)
    @Html.ValidationSummary(true)

    /*Contact Info*/
    <p>Prefix: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Prefix)</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.FirstName)</p>
    <p>First Name*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.FirstName)</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.LastName)</p>
    <p>Last Name*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.LastName)</p>
    <p>Suffix: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Suffix)</p>

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Email)</p>
    <p>Email*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Email)</p>
    /*Set Email Type*/

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.PhoneNumber)</p>
    <p>Phone Number*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.PhoneNumber)</p>
    /*Set Phone Type*/

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.AddressLine1)</p>
    <p>Address Line 1*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.AddressLine1)</p>
    <p>Address Line 2: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.AddressLine2)</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.City)</p>
    <p>City*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.City)</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.State)</p>
    <p>State*: @Html.DropDownListFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.State, Model.States)</p>
    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.Zipcode)</p>
    <p>Zipcode*: @Html.EditorFor(m => m.ApplicationInfo.ApplicantContactInfo.Address.Zipcode)</p>
    /*Set Address Type*/

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.Position.PositionName)</p>
    <p>Desired Position*: @Html.DropDownListFor(m => m.ApplicationInfo.Position.PositionName, Model.Positions)</p>

    <p>@Html.LabelFor(m => m.ApplicationInfo.Experiences)</p>
    <p>Company: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].Company)</p>
    <p>Title: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].Title)</p>
    <p>City: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].Location.City)</p>
    <p>State: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].Location.State)</p>
    <p>Start Date: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].StartDate)</p>
    <p>End Date: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].EndDate)</p>
    <p>Supervisor Name: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].SupervisorName)</p>
    <p>Supervisor Phone Number: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].SupervisorPhone)</p>
    <p>Supervisor Email: @Html.EditorFor(m => m.ApplicationInfo.Experiences[0].SupervisorEmail)</p>


    //<p>Education Degree: @Html.DropDownListFor(m => m.ApplicationInfo.Education, Model.Degrees)</p>

    <p>@Html.ValidationMessageFor(m => m.ApplicationInfo.DesiredSalary)</p>
    <p>Desired Salary*: @Html.EditorFor(m => m.ApplicationInfo.DesiredSalary)</p>

    <p>Date of Application: @Html.EditorFor(m => m.ApplicationInfo.AppDate)</p>
    <button class="btn btn-primary">Submit</button>
}

HRPortal.UI/Views/Applicant/Index.cshtml
@model HRPortal.Models.Resume

@{
    ViewBag.Title = "Applicant Main Page";
}

<h2>Welcome to the Application Page!</h2>

<div>
    <!--may add ID to null-->
    @Html.ActionLink("Create A New Application", "CreateApp", "Applicant", null, new { @class = "btn btn-primary" })
</div>