HRPortal.UI/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.UI.Models;

namespace HRPortal.UI.Controllers
{
    public class PoliciesController : Controller
    {
        private RepoOperations _rops;

        // GET: Policies
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManagePolicies()
        {
            _rops = new RepoOperations();
            var policiesVm = new ViewPoliciesVM(_rops.ReturnListOfPolicyCategories(), _rops.ReturnAllPolicies());

            return View(policiesVm);
        }

        public ActionResult AddPolicyToNewCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPolicyInCategory(string categoryId)
        {
            _rops = new RepoOperations();
            var newPolicyVm = new CreatePolicyVM(_rops.ReturnListOfPolicyCategories());
            //newPolicyVm.CreatePolicyCatList(_rops.ReturnListOfPolicyCategories());
            newPolicyVm.Policy.Category.CategoryId = int.Parse(categoryId);

            return View(newPolicyVm);
        }

        [HttpPost]
        public ActionResult SubmitNewPolicyInCat(CreatePolicyVM vM)
        {
            _rops = new RepoOperations();
            vM.Policy.DateCreated = DateTime.Now.Date;
            //if (ModelState.IsValid)
            //{
                var complete = _rops.AddNewPolicy(vM.Policy);

                return View("Confirmation", complete);
            //}

            //return View("AddPolicyInCategory", vM);
        }

        public ActionResult ViewPoliciesInCategory(int id)
        {
            _rops = new RepoOperations();
            var policies = _rops.ReturnAllPolicies().Where(p => p.Category.CategoryId == id).ToList();

            return View(policies);
        }


        public ActionResult ManageCategories()
        {
            return View();
        }

        public ActionResult ViewAllPolicies()
        {
            return View();
        }
    }
}

HRPortal.UI/Controllers/PolicyController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using HRPortal.BLL;
//using HRPortal.UI.Models;

//namespace HRPortal.UI.Controllers
//{
//    public class PolicyController : Controller
//    {
//        private RepoOperations _rops = new RepoOperations();

//        // GET: Policy
//        public ActionResult Index()
//        {
//            return View();
//        }

        
//        //Methods for View Policies tab
//        public ActionResult ViewAllPolicies()
//        {
//            var viewPolicies = new ViewPoliciesVM();

//            viewPolicies.CreatePolicyCatList(_rops.ReturnListOfPolicyCategories());

//            return View("ViewCategories", viewPolicies);
//        }

//        //[HttpPost]
//        //public ActionResult ViewAllPolicies(ViewPoliciesVM viewPolicies)
//        //{
//        //    viewPolicies.Policies = _rops.ReturnListOfPoliciesInCategory(viewPolicies.PolicyCategory);

//        //    return View("ViewAllPolicies", viewPolicies);
//        //}

//        public ActionResult ViewPolicyDetails(int policyId)
//        {
//            var policy = _rops.ReturnPolicyById(policyId);

//            return View(policy);
//        }



//        //Methods for Manage Policies tab
//        public ActionResult ManagePolicies()
//        {
//            var viewPolicies = new ViewPoliciesVM();
//            viewPolicies.CreatePolicyCatList(_rops.ReturnListOfPolicyCategories());

//            return View(viewPolicies);
//        }

//        //[HttpPost]
//        //public ActionResult ManagePoliciesInCategory(ViewPoliciesVM viewPolicies)
//        //{
//        //    viewPolicies.Policies = _rops.ReturnListOfPoliciesInCategory(viewPolicies.PolicyCategory);

//        //    return View(viewPolicies);
//        //}

//        public ActionResult ViewPolicyDetailsFromMP(int policyId)
//        {
//            var policy = _rops.ReturnPolicyById(policyId);

//            return View(policy);
//        }

//        //public ActionResult DeletePolicy(int policyId, string category)
//        //{
//        //    _rops.RemovePolicyByIdOp(policyId);
//        //    var viewPolicies = new ViewPoliciesVM();
//        //    viewPolicies.PolicyCategory.CategoryTitle = category;
//        //    viewPolicies.Policies = _rops.ReturnListOfPoliciesInCategory(viewPolicies.PolicyCategory);

//        //    if (viewPolicies.Policies.Count() != 0)
//        //    {
//        //        return View("ManagePoliciesInCategory", viewPolicies);
//        //    }
//        //    else
//        //    {
//        //        return View("Index");
//        //    }
//        //}


//        //Methods For Add New Policy in Manage Policies tab
//        public ActionResult AddNewPolicy()
//        {
//            var newPolicy = new CreatePolicyVM();
//            newPolicy.CreatePolicyCatList(_rops.ReturnListOfPolicyCategories());
//            //newPolicy.Policy.PolicyId = _rops.HighestPolicyIdNum() + 1;
//            return View(newPolicy);
//        }

//        [HttpPost]
//        public ActionResult AddNewPolicy(CreatePolicyVM newPolicy)
//        {
//            return View("CreateNewPolicyInExistingCat", newPolicy);
//        }


//        [HttpPost]
//        public ActionResult CreateNewPolicyInExistingCat(CreatePolicyVM newPolicy)
//        {
//            newPolicy.Policy.PolicyId = _rops.HighestPolicyIdNum() + 1;

//            if (ModelState.IsValid)
//            {
//                _rops.AddNewPolicyInExistingCat(newPolicy.Policy);

//                return View("Confirmation", newPolicy.Policy);
//            }

//            return View(newPolicy);
//        }

//        public ActionResult AddNewCategoryAndPolicy()
//        {
//            var newPolicy = new CreatePolicyVM();
//            newPolicy.CreatePolicyCatList(_rops.ReturnListOfPolicyCategories());
//            newPolicy.Policy.PolicyId = _rops.HighestPolicyIdNum() + 1;

//            return View(newPolicy);
//        }

//        [HttpPost]
//        public ActionResult AddNewCategoryAndPolicy(CreatePolicyVM newPolicy)
//        {
//            if (ModelState.IsValid)
//            {
//                _rops.AddNewPolicyInNewCat(newPolicy.Policy);

//                return View("Confirmation", newPolicy.Policy);
//            }
//            return View(newPolicy);
//        }

//        //Methods for Manage Categories tab
//        public ActionResult ManageCategories()
//        {
//            var viewPolicies = new ViewPoliciesVM();
//            viewPolicies.CreatePolicyCatList(_rops.ReturnListOfPolicyCategories());

//            return View(viewPolicies);
//        }
        
//    }
//}

HRPortal.UI/Views/Policies/AddPolicyInCategory.cshtml
@model HRPortal.UI.Models.CreatePolicyVM

@{
    ViewBag.Title = "Add Policy To an Existing Category";
}

<h2>Add Policy To an Existing Category</h2>

<div class="container">
    <div class="row">
        <div class="panel panel-body">
            @using (Html.BeginForm("SubmitNewPolicyInCat", "Policies", null, FormMethod.Post, new {@id = "addpolicyexistform" }))
            {
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.ValidationMessageFor(m => m.Policy.Title)
                    @Html.LabelFor(m => m.Policy.Title, "Policy Title", new {@class = "control-label"})
                    @Html.TextBoxFor(m => m.Policy.Title, new {@class = "form-control"})
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Policy.Category.CategoryTitle, "Category", new {@class = "control-label"})
                    @Html.DropDownListFor(m => m.Policy.Category.CategoryId, Model.PolCatsList, new {@class = "form-control"})
                </div>

                <div class="form-group">
                    @Html.ValidationMessageFor(m => m.Policy.ContentText)
                    @Html.LabelFor(m => m.Policy.ContentText, "Content Text", new {@class = "control-label"})
                    @Html.TextAreaFor(m => m.Policy.ContentText, new {@class = "form-control", @rows = "10"})
                </div>

                <button type="reset" class="btn btn-danger">RESET</button>
                <button type="Submit" class="btn btn-success">Submit</button>
            }
        </div>
        </div>
</div>
<br />
<div>
    @Html.ActionLink("Return to Policy Index Page", "Index", "Policies", null, new {@class = "btn btn-warning"})
</div>

@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/app/jquery-validate-default.js"></script>
    <script src="~/Scripts/app/addpolicyexistingcategory.js"></script>
}

HRPortal.UI/Views/Policies/Confirmation.cshtml
@model HRPortal.Models.Policy

@{
    ViewBag.Title = "Confirmation";
}

<h2>Confirmation</h2>

<p>You have successfully added a new Policy!!</p>
<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <td><b>Field</b></td>
                <td><b>Value</b></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Policy ID</td>
                <td>@Html.DisplayFor(m => m.PolicyId)</td>
            </tr>
            <tr>
                <td>Title</td>
                <td>@Html.DisplayFor(m => m.Title)</td>
            </tr>
        <tr>
            <td>Category Title</td>
            <td>@Html.DisplayFor(m => m.Category.CategoryTitle)</td>
        </tr>
        <tr>
        <td>Category ID</td>
        <td>@Html.DisplayFor(m => m.Category.CategoryId)</td>
        </tr>
        <tr>
            <td>Date Added</td>
            <td>@Html.DisplayFor(m => m.DateCreated)</td>
        </tr>
            <tr>
                <td>Content</td>
                <td>@Html.DisplayFor(m => m.ContentText)</td>
            </tr>
        </tbody>
    </table>
</div>
<br />
<div>
    @Html.ActionLink("Return to Policies Index Page", "Index", "Policies", null, new { @class = "btn btn-warning" })
</div>

HRPortal.UI/Views/Policies/Index.cshtml
@{
    ViewBag.Title = "Policy Management Index";
}

<h2 class="text-center">Policy Management Index</h2>
<br/>
<div class="row">
    <div class="btn-group btn-group-justified">
        @Html.ActionLink("View Policies", "ViewAllPolicies", "Policies", null, new {@class = "btn btn-primary"})

        @Html.ActionLink("Manage Policies", "ManagePolicies", "Policies", null, new {@class = "btn btn-primary"})

        @Html.ActionLink("Manage Categories", "ManageCategories", "Policies", null, new {@class = "btn btn-primary"})
    </div>
</div>

HRPortal.UI/Views/Policies/ManagePolicies.cshtml
@model HRPortal.UI.Models.ViewPoliciesVM

@{
    ViewBag.Title = "Manage Policies";
}

<h2>Manage Policies</h2>
<div class="container">
    @*View/Manage policies in a category*@
    <div class="panel">
        <div class="row panel-body">
            <div class="btn-group">
                <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                    Select a Category to Manage Its Policies
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @foreach (var c in Model.PolicyCategories)
                    {
                        <li><a href="/Policies/ViewPoliciesInCategory/@c.CategoryId">@c.CategoryTitle</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>


    
    @*Add policies options*@
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>Add a New Policy</h4></div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.ActionLink("Add New Policy in New Category", "AddPolicyToNewCategory", "Policies", null, new {@class = "btn btn-success"})
                </div>
                <br/>
                <div class="form-group">
                    @using (Html.BeginForm("AddPolicyInCategory", "Policies", null, FormMethod.Post, null))
                    {
                        <p>Or choose an existing Category to add a new policy to from below:</p>
                         @Html.DropDownList("categoryId", Model.PolicyCategoriesList, new { @class = "form-control" })
                        <br/>
                         <button class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Add New Policy to Category Selected</button>
                    }
                </div>
            </div>
    </div>
    <br />
    <div>
        @Html.ActionLink("Return to Policies Index Page", "Index", "Policies", null, new { @class = "btn btn-danger" })
    </div>
</div>

HRPortal.UI/Views/Policies/ViewPoliciesInCategory.cshtml
@model List<HRPortal.Models.Policy>

@{
    ViewBag.Title = "View Policies In Category";
}

<h2>View Policies In @Model[0].Category.CategoryTitle</h2>

<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Policy Title</td>
                <td>Policy Category</td>
                <td>Policy ID#</td>
                <td>Date Created</td>
                <td>Link</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => p.Title)</td>
                    <td>@Html.DisplayFor(m => p.Category.CategoryTitle)</td>
                    <td>@Html.DisplayFor(m => p.PolicyId)</td>
                    <td>@Html.DisplayFor(m => p.DateCreated)</td>
                    <td>@Html.ActionLink("Details", "ViewPolicyDetails", "Policies", new { @p.PolicyId }, new { @class = "btn btn-primary" })</td>
                </tr>
            }
        </tbody>
    </table>
</div>